property_positive:
  name: 'Filter 1'
  category: 'Nekustamie īpašumi'
  sub_categories:
    - sub_category:
      title: 'Nekustamie īpašumi'
      option: 'Biroji'
    - sub_category:
      title: 'Biroji'
      option: 'Balvi un rajons'
    - sub_category:
      title: 'Balvi un rajons'
      option: 'Balvi'
    - sub_category:
      title: 'Darbība'
      option: 'Visi'
  parameters:
    - parameter:
      name: 'CENA (EUR)'
      left: '1'
      right: '1000'
    - parameter:
      name: 'PLATĪBA (M2)'
      left: '1'
      right: '3000'
