property_filter:
  name: 'Filter 1'
  category: 'Nekustamie īpašumi'
  sub_categories:
    - sub_category:
      title: 'Nekustamie īpašumi'
      option: 'Zeme'
    - sub_category:
      title: 'Zeme'
      option: 'Jūrmala'
    - sub_category:
      title: 'Jūrmala'
      option: 'Bulduri'
    - sub_category:
      title: 'Darbība'
      option: 'Pērk'
  parameters_positive:
    - parameter:
      name: 'NOSAUKUMS'
      filter_name: 'name or... or, bla?'
    - parameter:
      name: 'CENA (EUR)'
      left: '1'
      right: '1000'
    - parameter:
      name: 'PLATĪBA (M2)'
      left: '1'
      right: '3000'
  parameters_negative:
    - parameter:
      name: 'NOSAUKUMS'
      filter_name: ''
    - parameter:
      name: 'CENA (EUR)'
      left: ''
      right: ''
    - parameter:
      name: 'PLATĪBA (M2)'
      left: ''
      right: ''
  
